services:
  - type: web
    name: smartbot-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
        
